name: reema-patrick
favicon: null
layout_spectrum: 0.53531
typography_spectrum: 0.99077
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e2828'
    - '#bec9c5'
    - '#7d8f82'
    - '#e75954'
    - '#fd9891'
  brandStrength: 0
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose:
  - name: follow
    item: null
    url: null
